name: pad-ebank

services:
  account-service-db:
    image: postgres:17-alpine
    restart: no
    ports:
      - ${ACCOUNT_SERVICE_DB_PORT}:5432
    volumes:
      - account-service-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: ${ACCOUNT_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
    networks:
      - ebank-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "account_db" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  account-service-db-exporter:
    image: prometheuscommunity/postgres-exporter
    depends_on:
      account-service-db:
        condition: service_started
    environment:
      DATA_SOURCE_NAME: postgres://${ACCOUNT_SERVICE_DB_USER}:${ACCOUNT_SERVICE_DB_PASSWORD}@account-service-db:5432/account_db?sslmode=disable
    networks:
      - ebank-network

  account-service:
    depends_on:
      account-service-db:
        condition: service_started
    build:
      context: ${ACCOUNT_SERVICE_PATH}
    env_file:
      - ${ACCOUNT_SERVICE_ENV_PATH}
    restart: no
    scale: 1
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3200:3200"
    init: true
    networks:
      - ebank-network

  account-service-unhealthy:
    depends_on:
      - account-service-db
    build:
      context: ${ACCOUNT_SERVICE_PATH}
    env_file:
      - ${ACCOUNT_SERVICE_ENV_PATH}
    restart: no
    init: true
    environment:
      UNHEALTHY: true
    networks:
      - ebank-network

  transaction-service:
    depends_on:
      transaction-service-db:
        condition: service_started
    build:
      context: ${TRANSACTION_SERVICE_PATH}
    env_file:
      - ${TRANSACTION_SERVICE_ENV_PATH}
    init: true
    ports:
      - "4000:3000"
      - "4100:3100"
    networks:
      - ebank-network

  transaction-service-db:
    image: postgres:17-alpine
    restart: no
    ports:
      - ${TRANSACTION_SERVICE_DB_PORT}:5432
    volumes:
      - transaction-service-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: ${TRANSACTION_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${TRANSACTION_SERVICE_DB_PASSWORD}
    networks:
      - ebank-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "account_db" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s


  transaction-service-db-exporter:
    image: prometheuscommunity/postgres-exporter
    depends_on:
      transaction-service-db:
        condition: service_started
    environment:
      DATA_SOURCE_NAME: postgres://${TRANSACTION_SERVICE_DB_USER}:${TRANSACTION_SERVICE_DB_PASSWORD}@transaction-service-db:5432/transaction_db?sslmode=disable
    networks:
      - ebank-network

  shared-cache:
    image: redis:alpine
    restart: no
    ports:
      - ${CACHE_PORT}:6379
    volumes:
      - cache-data:/data
    environment:
      - REDIS_PASSWORD=${CACHE_PASSWORD}
    networks:
      - ebank-network

  shared-cache-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=shared-cache:6379
    depends_on:
      shared-cache:
        condition: service_started
    networks:
      - ebank-network

  service-discovery:
    build:
      context: ${SERVICE_DISCOVERY_PATH}
      dockerfile: Dockerfile
    depends_on:
      - shared-cache
    tty: true
    restart: no
    env_file:
      - ${SERVICE_DISCOVERY_ENV_PATH}
    ports:
      - "5000:3000"
    networks:
      - ebank-network

  gateway:
    build:
      context: ${GATEWAY_PATH}
      dockerfile: Dockerfile
    depends_on:
      - shared-cache
    tty: true
    restart: no
    env_file:
      - ${GATEWAY_ENV_PATH}
    ports:
      - "7000:3000"
    networks:
      - ebank-network

  prometheus:
    image: prom/prometheus
    restart: no
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    depends_on:
      account-service-db-exporter:
        condition: service_started
      transaction-service-db-exporter:
        condition: service_started
      shared-cache-exporter:
        condition: service_started
      account-service:
        condition: service_healthy
      transaction-service:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
      gateway:
        condition: service_healthy
    networks:
      - ebank-network

  grafana:
    image: grafana/grafana
    restart: no
    ports:
      - "10000:3000"
    volumes:
      - grafana-data:/var/lib/grafana/
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - ebank-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  account-service-db-data:
  transaction-service-db-data:
  cache-data:
  prometheus-data:
  grafana-data:

networks:
  ebank-network:
    driver: bridge
    attachable: true
    enable_ipv6: false
    internal: false
