name: pad-ebank

services:
   account-service-db-pool:
      image: bitnami/pgpool:4
      ports: [ "5432:5432" ]
      environment:
         - PGPOOL_BACKEND_NODES=0:account-service-db-node-1:5432,1:account-service-db-node-2:5432,2:account-service-db-node-3:5432
         - PGPOOL_SR_CHECK_USER=${ACCOUNT_SERVICE_DB_USER}
         - PGPOOL_SR_CHECK_PASSWORD=${ACCOUNT_SERVICE_DB_PASSWORD}
         - PGPOOL_SR_CHECK_PERIOD=5
         - PGPOOL_HEALTH_CHECK_PERIOD=3
         - PGPOOL_HEALTH_CHECK_RETRY_DELAY=2
         - PGPOOL_HEALTH_CHECK_MAX_RETRIES=1
         - PGPOOL_HEALTH_CHECK_TIMEOUT=2
         - PGPOOL_MAX_POOL=32
         - PGPOOL_ENABLE_LDAP=no
         - PGPOOL_POSTGRES_USERNAME=${ACCOUNT_SERVICE_DB_USER}
         - PGPOOL_POSTGRES_PASSWORD=${ACCOUNT_SERVICE_DB_PASSWORD}
         - PGPOOL_ADMIN_USERNAME=${ACCOUNT_SERVICE_DB_USER}
         - PGPOOL_ADMIN_PASSWORD=${ACCOUNT_SERVICE_DB_PASSWORD}
         - PGPOOL_ENABLE_LOAD_BALANCING=yes
         - PGPOOL_POSTGRES_CUSTOM_USERS=${ACCOUNT_SERVICE_DB_USER}
         - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=${ACCOUNT_SERVICE_DB_PASSWORD}
      healthcheck:
         test: [ "CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh" ]
         interval: 10s
         timeout: 5s
         retries: 2
      depends_on:
         - account-service-db-node-1
         - account-service-db-node-2
         - account-service-db-node-3
      networks: [ ebank-network ]

   account-service-db-node-1:
     &account-service-db-node-common
      image: bitnami/postgresql-repmgr:16
      environment:
         POSTGRESQL_POSTGRES_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
         POSTGRESQL_USERNAME: ${ACCOUNT_SERVICE_DB_USER}
         POSTGRESQL_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
         POSTGRESQL_DATABASE: ${ACCOUNT_SERVICE_DB_NAME}
         POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 2
         REPMGR_PRIMARY_HOST: account-service-db-node-1
         REPMGR_PARTNER_NODES: account-service-db-node-1,account-service-db-node-2,account-service-db-node-3
         REPMGR_NODE_NAME: account-service-db-node-1
         REPMGR_NODE_NETWORK_NAME: account-service-db-node-1
         REPMGR_USERNAME: ${ACCOUNT_SERVICE_DB_USER}
         REPMGR_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
         REPMGR_CONNECT_TIMEOUT: 2
         REPMGR_RECONNECT_ATTEMPTS: 1
         REPMGR_RECONNECT_INTERVAL: 2
         REPMGR_MASTER_RESPONSE_TIMEOUT: 5
      volumes: [ account-service-db-node-1-data:/bitnami/postgresql ]
      ports: [ "5433:5432" ]
      networks: [ ebank-network ]
      healthcheck:
         test: [ "CMD-SHELL", "pg_isready -U ${ACCOUNT_SERVICE_DB_USER} -d ${ACCOUNT_SERVICE_DB_NAME} -h localhost" ]
         interval: 10s
         timeout: 5s
         retries: 3

   account-service-db-node-2:
      <<: *account-service-db-node-common
      environment:
         POSTGRESQL_POSTGRES_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
         POSTGRESQL_USERNAME: ${ACCOUNT_SERVICE_DB_USER}
         POSTGRESQL_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
         POSTGRESQL_DATABASE: ${ACCOUNT_SERVICE_DB_NAME}
         POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 2
         REPMGR_PRIMARY_HOST: account-service-db-node-1
         REPMGR_PARTNER_NODES: account-service-db-node-1,account-service-db-node-2,account-service-db-node-3
         REPMGR_NODE_NAME: account-service-db-node-2
         REPMGR_NODE_NETWORK_NAME: account-service-db-node-2
         REPMGR_USERNAME: ${ACCOUNT_SERVICE_DB_USER}
         REPMGR_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
         REPMGR_CONNECT_TIMEOUT: 2
         REPMGR_RECONNECT_ATTEMPTS: 1
         REPMGR_RECONNECT_INTERVAL: 2
         REPMGR_MASTER_RESPONSE_TIMEOUT: 5
      volumes: [ account-service-db-node-2-data:/bitnami/postgresql ]
      ports: [ "5434:5432" ]

   account-service-db-node-3:
      <<: *account-service-db-node-common
      environment:
         POSTGRESQL_POSTGRES_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
         POSTGRESQL_USERNAME: ${ACCOUNT_SERVICE_DB_USER}
         POSTGRESQL_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
         POSTGRESQL_DATABASE: ${ACCOUNT_SERVICE_DB_NAME}
         POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 2
         REPMGR_PRIMARY_HOST: account-service-db-node-1
         REPMGR_PARTNER_NODES: account-service-db-node-1,account-service-db-node-2,account-service-db-node-3
         REPMGR_NODE_NAME: account-service-db-node-3
         REPMGR_NODE_NETWORK_NAME: account-service-db-node-3
         REPMGR_USERNAME: ${ACCOUNT_SERVICE_DB_USER}
         REPMGR_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
         REPMGR_CONNECT_TIMEOUT: 2
         REPMGR_RECONNECT_ATTEMPTS: 1
         REPMGR_RECONNECT_INTERVAL: 2
         REPMGR_MASTER_RESPONSE_TIMEOUT: 5
      volumes: [ account-service-db-node-3-data:/bitnami/postgresql ]
      ports: [ "5435:5432" ]

   transaction-service-db:
      image: postgres:17-alpine
      environment:
         POSTGRES_DB: transaction_db
         POSTGRES_USER: ${TRANSACTION_SERVICE_DB_USER}
         POSTGRES_PASSWORD: ${TRANSACTION_SERVICE_DB_PASSWORD}
      volumes:
         - transaction-service-db-data:/var/lib/postgresql/data
      networks: [ ebank-network ]
      ports: [ "5436:5432" ]

   account-service:
     &account-service-common
      depends_on: [ account-service-db-pool ]
      build:
         context: ${ACCOUNT_SERVICE_PATH}
      env_file: [ "${ACCOUNT_SERVICE_ENV_PATH}" ]
      scale: 1
      ports: [ "3000:3000", "3100:3100", "3200:3200" ]
      init: true
      networks: [ ebank-network ]

   account-service-unhealthy:
      <<: *account-service-common
      environment:
         UNHEALTHY: true
      ports: [ ]

   transaction-service:
      depends_on: [ transaction-service-db ]
      build:
         context: ${TRANSACTION_SERVICE_PATH}
      env_file: [ "${TRANSACTION_SERVICE_ENV_PATH}" ]
      init: true
      ports: [ "4000:3000", "4100:3100" ]
      networks: [ ebank-network ]

   service-discovery:
      build:
         context: ${SERVICE_DISCOVERY_PATH}
         dockerfile: Dockerfile
      tty: true
      env_file: [ "${SERVICE_DISCOVERY_ENV_PATH}" ]
      ports: [ "5000:3000" ]
      networks: [ ebank-network ]

   gateway:
      build:
         context: ${GATEWAY_PATH}
         dockerfile: Dockerfile
      tty: true
      env_file: [ "${GATEWAY_ENV_PATH}" ]
      ports: [ "7000:3000" ]
      networks: [ ebank-network ]

   prometheus:
      image: prom/prometheus
      ports: [ "9090:9090" ]
      volumes:
         - ./config/prometheus/:/etc/prometheus/
         - prometheus-data:/prometheus
      networks: [ ebank-network ]

   grafana:
      image: grafana/grafana
      ports: [ "10000:3000" ]
      volumes: [ grafana-data:/var/lib/grafana/ ]
      environment:
         - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
         - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      depends_on: [ prometheus ]
      networks: [ ebank-network ]


   redis-node-1:
     &redis-master
      image: redis:alpine
      command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
      volumes: [ ./config/redis:/usr/local/etc/redis ]
      networks: [ ebank-network ]
      ports: [ "6379:6379" ]
   redis-node-2:
      <<: *redis-master
      ports: [ "6380:6379" ]
   redis-node-3:
      <<: *redis-master
      ports: [ "6381:6379" ]

   redis-node-4:
     &redis-slave
      image: redis:alpine
      command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD}
      volumes: [ ./config/redis:/usr/local/etc/redis ]
      networks: [ ebank-network ]
      ports: [ "6382:6379" ]
   redis-node-5:
      <<: *redis-slave
      ports: [ "6383:6379" ]
   redis-node-6:
      <<: *redis-slave
      ports: [ "6384:6379" ]

   redis-cluster-creator:
      image: redis:alpine
      command: >
         redis-cli
         -a ${REDIS_PASSWORD}
         --cluster create
         redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379
         --cluster-replicas 1
         --cluster-yes
      depends_on:
         - redis-node-1
         - redis-node-2
         - redis-node-3
         - redis-node-4
         - redis-node-5
         - redis-node-6
      networks: [ ebank-network ]

volumes:
   account-service-db-node-1-data: { }
   account-service-db-node-2-data: { }
   account-service-db-node-3-data: { }
   transaction-service-db-data: { }
   prometheus-data: { }
   grafana-data: { }

networks:
   ebank-network: { }
