name: pad-ebank

services:
  account-service-db:
    image: postgres:latest
    restart: no
    ports:
      - ${ACCOUNT_SERVICE_DB_PORT}:5432
    volumes:
      - account-service-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: ${ACCOUNT_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
    networks:
      - ebank-network

  account-service:
    depends_on:
      - account-service-db
    build:
      context: ${ACCOUNT_SERVICE_PATH}
      dockerfile: ${ACCOUNT_SERVICE_DOCKERFILE}
    restart: no
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ${ACCOUNT_SERVICE_PATH}/:/app/
    networks:
      - ebank-network

  transaction-service:
    depends_on:
      - transaction-service-db
    build:
      context: ${TRANSACTION_SERVICE_PATH}
      dockerfile: ${TRANSACTION_SERVICE_DOCKERFILE}
    restart: no
    ports:
      - "4000:3000"
    volumes:
      - ${TRANSACTION_SERVICE_PATH}/:/app/
    networks:
      - ebank-network

  transaction-service-db:
    image: postgres:latest
    restart: no
    ports:
      - ${TRANSACTION_SERVICE_DB_PORT}:5432
    volumes:
      - transaction-service-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: ${TRANSACTION_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${TRANSACTION_SERVICE_DB_PASSWORD}
    networks:
      - ebank-network

  shared-cache:
    image: redis
    restart: no
    ports:
      - ${CACHE_PORT}:6379
    volumes:
      - cache-data:/data
    environment:
      - REDIS_PASSWORD=${CACHE_PASSWORD}
    networks:
      ebank-network:

volumes:
  account-service-db-data:
  transaction-service-db-data:
  cache-data:

networks:
  ebank-network:
