name: pad-ebank-dev

services:
  account-service-db:
    image: postgres:17-alpine
    restart: no
    ports:
      - ${ACCOUNT_SERVICE_DB_PORT}:5432
    volumes:
      - account-service-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: ${ACCOUNT_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_SERVICE_DB_PASSWORD}
    networks:
      - ebank-network-dev

  account-service:
    depends_on:
      - account-service-db
      - service-discovery
    build:
      context: ${ACCOUNT_SERVICE_PATH}
      dockerfile: Dockerfile.development
    env_file:
      - ${ACCOUNT_SERVICE_ENV_PATH}
    restart: no
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3200:3200"
    volumes:
      - ${ACCOUNT_SERVICE_PATH}/src/:/app/src/
    networks:
      - ebank-network-dev

  transaction-service:
    depends_on:
      - transaction-service-db
      - service-discovery
      - account-service
    build:
      context: ${TRANSACTION_SERVICE_PATH}
      dockerfile: Dockerfile.development
    env_file:
      - ${TRANSACTION_SERVICE_ENV_PATH}
    ports:
      - "4000:3000"
      - "4100:3100"
    volumes:
      - ${TRANSACTION_SERVICE_PATH}/src/:/app/src/
    networks:
      - ebank-network-dev

  transaction-service-db:
    image: postgres:17-alpine
    restart: no
    ports:
      - ${TRANSACTION_SERVICE_DB_PORT}:5432
    volumes:
      - transaction-service-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: ${TRANSACTION_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${TRANSACTION_SERVICE_DB_PASSWORD}
    networks:
      - ebank-network-dev

  shared-cache:
    image: redis:alpine
    restart: no
    ports:
      - ${CACHE_PORT}:6379
    volumes:
      - cache-data:/data
    environment:
      - REDIS_PASSWORD=${CACHE_PASSWORD}
    networks:
      - ebank-network-dev

  service-discovery:
    build:
      context: ${SERVICE_DISCOVERY_PATH}
      dockerfile: Dockerfile.development
    restart: no
    env_file:
      - ${SERVICE_DISCOVERY_ENV_PATH}
    ports:
      - "5000:3000"
    volumes:
      - ${SERVICE_DISCOVERY_PATH}/:/app/
    networks:
      - ebank-network-dev
    depends_on:
      - shared-cache

  gateway:
    build:
      context: ${GATEWAY_PATH}
      dockerfile: Dockerfile.development
    restart: no
    env_file:
      - ${GATEWAY_ENV_PATH}
    ports:
      - "7000:3000"
    volumes:
      - ${GATEWAY_PATH}/:/app/
    networks:
      - ebank-network-dev
    depends_on:
      - shared-cache
      - service-discovery
      - account-service
      - transaction-service

volumes:
  account-service-db-data:
    driver: local
  transaction-service-db-data:
    driver: local
  cache-data:
    driver: local

networks:
  ebank-network-dev:
    driver: bridge
    attachable: true
    enable_ipv6: false
    internal: false
