global:
  scrape_interval: 5s
  scrape_timeout: 500ms

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: shared-cache
    static_configs:
      - targets: [ 'shared-cache-exporter:9121' ]

  - job_name: account-service
    http_sd_configs:
      - url: http://service-discovery:3000/api/v1/registry/account-service?format=prometheus
    metrics_path: /api/v1/metrics

  - job_name: transaction-service
    http_sd_configs:
      - url: http://service-discovery:3000/api/v1/registry/transaction-service?format=prometheus
    metrics_path: /api/v1/metrics

  - job_name: account-service-db
    static_configs:
      - targets: [ 'account-service-db-exporter:9187' ]

  - job_name: transaction-service-db
    static_configs:
      - targets: [ 'transaction-service-db-exporter:9187' ]

  - job_name: service-discovery
    static_configs:
      - targets: [ 'service-discovery:3000' ]

  - job_name: gateway
    static_configs:
      - targets: [ 'gateway:3000' ]
